### PR TITLE
Small changes to the git structure 

### PR DESCRIPTION
**Pull request by MariaDukmak**
Added 'pre-commit', '.env.example' files. Also updated setup.py and Readme.md.

Because:

These changes were nessery to make the repo easier to use.
pre-commit: makes it able to check the code before commit.
env.example: makes the developer settings more according to the guidelines.

### CODE REVIEW

**Comment by BKBetz** [comment]
mooi

**Comment by AHipWhale** [comment]
I don't like your commit message

**Review by BKBetz — APPROVED** [review]
Looks good

**Review by AHipWhale — APPROVED** [review]
A lot of commits

**Pull request merged**
